Map<String, String> weatherImages = {
  'Blizzard': 'assets/Blizzard.jpg',
  'Blowing snow': 'assets/Blowing snow.jpg',
  'Clear': 'assets/Clear.jpg',
  'Sunny': 'assets/Clear.jpg',
  'Cloudy': 'assets/Cloudy.jpg',
  'Fog': 'assets/Fog.jpg',
  'Freezing drizzle': 'assets/Freezing drizzle.jpg',
  'Freezing fog': 'assets/Freezing fog.jpg',
  'Heavy freezing drizzle': 'assets/Heavy freezing drizzle.jpg',
  'Heavy rain': 'assets/Heavy rain.jpg',
  'Heavy snow': 'assets/Heavy snow.jpg',
  'Ice pellets': 'assets/Ice pellets.jpg',
  'Light drizzle': 'assets/Light drizzle.jpg',
  'Light rain': 'assets/Light drizzle.jpg',
  'Light freezing rain': 'assets/Light freezing rain.jpg',
  'Light rain shower': 'assets/Light rain shower.jpg',
  'Light showers of ice pellets': 'assets/Light showers of ice pellets.jpg',
  'Light sleet showers': 'assets/Light sleet showers.jpg',
  'Light snow': 'assets/Light snow.jpg',
  'Light snow showers': 'assets/Light snow showers.jpg',
  'Mist': 'assets/Mist.jpg',
  'Moderate or heavy freezing rain': 'assets/Moderate or heavy freezing rain.jpg',
  'Moderate or heavy rain shower': 'assets/Moderate or heavy rain shower.jpg',
  'Moderate or heavy rain with thunder': 'assets/Moderate or heavy rain with thunder.jpg',
  'Moderate or heavy showers of ice pellets': 'assets/Moderate or heavy showers of ice pellets.jpg',
  'Moderate or heavy sleet': 'assets/Moderate or heavy sleet.jpg',
  'Moderate or heavy sleet showers': 'assets/Moderate or heavy sleet showers.jpg',
  'Moderate or heavy snow showers': 'assets/Moderate or heavy snow showers.jpg',
  'Moderate or heavy snow with thunder': 'assets/Moderate or heavy snow with thunder.jpg',
  'Moderate rain': 'assets/Moderate rain.jpg',
  'Moderate rain at times': 'assets/Moderate rain at times.jpg',
  'Moderate snow': 'assets/Moderate snow.jpg',
  'Overcast': 'assets/Overcast.jpg',
  'Partly cloudy': 'assets/Partly cloudy.jpg',
  'Patchy freezing drizzle possible': 'assets/Patchy freezing drizzle possible.jpg',
  'Patchy heavy snow': 'assets/Patchy heavy snow.jpg',
  'Patchy light drizzle': 'assets/Patchy light drizzle.jpg',
  'Patchy light rain': 'assets/Patchy light rain.jpg',
  'Patchy light rain with thunder': 'assets/Patchy light rain with thunder.jpg',
  'Patchy light snow': 'assets/Patchy light snow.jpg',
  'Patchy light snow with thunder': 'assets/Patchy light snow with thunder.jpg',
  'Patchy moderate snow': 'assets/Patchy moderate snow.jpg',
  'Patchy rain possible': 'assets/Patchy rain possible.jpg',
  'Patchy sleet possible': 'assets/Patchy sleet possible.jpg',
  'Patchy snow possible': 'assets/Patchy snow possible.jpg',
  'Thundery outbreaks possible': 'assets/Thundery outbreaks possible.jpg',
  'Torrential rain shower': 'assets/Torrential rain shower.jpg',
};